spring:
  datasource:
    url: jdbc:mysql://10.10.11.86:3306/test?useUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: yu2071673
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.ecdata.demo.pojo
